trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# =========================
# CI STAGE
# =========================
- stage: CI
  displayName: 'Build and Test'

  jobs:

  # -------------------------
  # FRONTEND
  # -------------------------
  - job: Frontend
    displayName: 'Frontend Build'

    steps:
    - checkout: self

    - task: NodeTool@0
      displayName: 'Install Node.js 22'
      inputs:
        versionSpec: '22.x'

    - script: |
        cd Frontend
        npm ci
        npm run build
      displayName: 'Install and Build Frontend'


  # -------------------------
  # BACKEND
  # -------------------------
  - job: Backend
    displayName: 'Backend Build and Test'

    steps:
    - checkout: self

    - task: JavaToolInstaller@0
      displayName: 'Install Java 21'
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        cd Backend
        chmod +x mvnw
        ./mvnw clean test
        ./mvnw package -DskipTests
      displayName: 'Build and Test Spring Boot Backend'