/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FreeSessionRouteImport } from './routes/free-session'
import { Route as HealthRiskCalculatorRouteImport } from './routes/health-risk-calculator'
import { Route as HealthVaultRouteImport } from './routes/health-vault'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor_.availability'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as ServicesCouplesTherapyRouteImport } from './routes/services.couples-therapy'
import { Route as BlogsBlogIdIndexRouteImport } from './routes/blogs.$blogId.index'
import { Route as DoctorsDoctorIdIndexRouteImport } from './routes/doctors.$doctorId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeSessionRoute = FreeSessionRouteImport.update({
  id: '/free-session',
  path: '/free-session',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRiskCalculatorRoute = HealthRiskCalculatorRouteImport.update({
  id: '/health-risk-calculator',
  path: '/health-risk-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthVaultRoute = HealthVaultRouteImport.update({
  id: '/health-vault',
  path: '/health-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/doctor_/availability',
  path: '/doctor/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCouplesTherapyRoute = ServicesCouplesTherapyRouteImport.update({
  id: '/services/couples-therapy',
  path: '/services/couples-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdIndexRoute = BlogsBlogIdIndexRouteImport.update({
  id: '/blogs/$blogId/',
  path: '/blogs/$blogId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdIndexRoute = DoctorsDoctorIdIndexRouteImport.update({
  id: '/doctors/$doctorId/',
  path: '/doctors/$doctorId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-session': typeof FreeSessionRoute
  '/health-risk-calculator': typeof HealthRiskCalculatorRoute
  '/health-vault': typeof HealthVaultRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/therapists': typeof TherapistsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/services/couples-therapy': typeof ServicesCouplesTherapyRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
  '/doctors/$doctorId/': typeof DoctorsDoctorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-session': typeof FreeSessionRoute
  '/health-risk-calculator': typeof HealthRiskCalculatorRoute
  '/health-vault': typeof HealthVaultRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/therapists': typeof TherapistsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/services/couples-therapy': typeof ServicesCouplesTherapyRoute
  '/blogs': typeof BlogsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/free-session': typeof FreeSessionRoute
  '/health-risk-calculator': typeof HealthRiskCalculatorRoute
  '/health-vault': typeof HealthVaultRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/therapists': typeof TherapistsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/doctor_/availability': typeof DoctorAvailabilityRoute
  '/services/couples-therapy': typeof ServicesCouplesTherapyRoute
  '/blogs/': typeof BlogsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
  '/doctors/$doctorId/': typeof DoctorsDoctorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/appointments'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/forgot-password'
    | '/free-session'
    | '/health-risk-calculator'
    | '/health-vault'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/therapists'
    | '/unauthorized'
    | '/doctor/availability'
    | '/services/couples-therapy'
    | '/blogs/'
    | '/doctors/'
    | '/blogs/$blogId/'
    | '/doctors/$doctorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/appointments'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/forgot-password'
    | '/free-session'
    | '/health-risk-calculator'
    | '/health-vault'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/therapists'
    | '/unauthorized'
    | '/doctor/availability'
    | '/services/couples-therapy'
    | '/blogs'
    | '/doctors'
    | '/blogs/$blogId'
    | '/doctors/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/appointments'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/forgot-password'
    | '/free-session'
    | '/health-risk-calculator'
    | '/health-vault'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/therapists'
    | '/unauthorized'
    | '/doctor_/availability'
    | '/services/couples-therapy'
    | '/blogs/'
    | '/doctors/'
    | '/blogs/$blogId/'
    | '/doctors/$doctorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DoctorRoute: typeof DoctorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreeSessionRoute: typeof FreeSessionRoute
  HealthRiskCalculatorRoute: typeof HealthRiskCalculatorRoute
  HealthVaultRoute: typeof HealthVaultRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  TherapistsRoute: typeof TherapistsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  ServicesCouplesTherapyRoute: typeof ServicesCouplesTherapyRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  BlogsBlogIdIndexRoute: typeof BlogsBlogIdIndexRoute
  DoctorsDoctorIdIndexRoute: typeof DoctorsDoctorIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-session': {
      id: '/free-session'
      path: '/free-session'
      fullPath: '/free-session'
      preLoaderRoute: typeof FreeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-risk-calculator': {
      id: '/health-risk-calculator'
      path: '/health-risk-calculator'
      fullPath: '/health-risk-calculator'
      preLoaderRoute: typeof HealthRiskCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-vault': {
      id: '/health-vault'
      path: '/health-vault'
      fullPath: '/health-vault'
      preLoaderRoute: typeof HealthVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor_/availability': {
      id: '/doctor_/availability'
      path: '/doctor/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/couples-therapy': {
      id: '/services/couples-therapy'
      path: '/services/couples-therapy'
      fullPath: '/services/couples-therapy'
      preLoaderRoute: typeof ServicesCouplesTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId/': {
      id: '/blogs/$blogId/'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId/'
      preLoaderRoute: typeof BlogsBlogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId/': {
      id: '/doctors/$doctorId/'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId/'
      preLoaderRoute: typeof DoctorsDoctorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DoctorRoute: DoctorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreeSessionRoute: FreeSessionRoute,
  HealthRiskCalculatorRoute: HealthRiskCalculatorRoute,
  HealthVaultRoute: HealthVaultRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  TherapistsRoute: TherapistsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  ServicesCouplesTherapyRoute: ServicesCouplesTherapyRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  BlogsBlogIdIndexRoute: BlogsBlogIdIndexRoute,
  DoctorsDoctorIdIndexRoute: DoctorsDoctorIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
